version: '3.8'

x-environment: &default_environment
  POSTGRES_USER: redash_user
  POSTGRES_PASSWORD: redash_password
  POSTGRES_DB: redash_db
  REDASH_DATABASE_URL: "postgresql://redash_user:redash_password@postgres:5432/redash_db"
  REDASH_REDIS_URL: "redis://redis:6379/0"
  REDASH_COOKIE_SECRET: "b94e8bd0ec961625d5c589da7da987c8"

services:
  redash:
    build: .
    container_name: redash
    environment:
      <<: *default_environment
    ports:
      - "80:5000"
    depends_on:
      - redash_init_db

  redash_worker:
    build: .
    container_name: redash_worker
    environment:
      <<: *default_environment
    command: ["./bin/docker-entrypoint", "worker"]
    depends_on:
      - redash_init_db

  redash_init_db:
    build: .
    container_name: redash_init_db
    environment:
      <<: *default_environment
    command:
      - /bin/sh
      - -c
      - |
        /app/bin/docker-entrypoint manage database create_tables &&
        /app/bin/docker-entrypoint manage users create_root admin@example.com admin --password admin
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      <<: *default_environment
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: redis
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
