version: 2.1

executors:
  google-sdk:
    docker:
      - image: google/cloud-sdk:427.0.0
    environment:
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKER_BUILDKIT: 1

build-docker-image-job: &build-docker-image-job
  docker:
    - image: circleci/node:14.17
  steps:
    - setup_remote_docker:
        version: 19.03.13
    - checkout
    - run: sudo apt update
    - run: sudo apt install python3-pip
    - run: .circleci/update_version
    - run: sudo npm install --global --force yarn@1.22.10
    - run: .circleci/docker_build
jobs:
  backend-lint:
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout
      - run: sudo pip install flake8
      - run: ./bin/flake8_tests.sh
  backend-unit-tests:
    environment:
      COMPOSE_FILE: .circleci/docker-compose.circle.yml
      COMPOSE_PROJECT_NAME: redash
    docker:
      - image: circleci/buildpack-deps:xenial
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - checkout
      - run:
          name: Build Docker Images
          command: |
            set -x
            COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build --build-arg skip_ds_deps=true --build-arg skip_frontend_build=true
            docker-compose up -d
            sleep 10
      - run:
          name: Create Test Database
          command: docker-compose run --rm postgres psql -h postgres -U postgres -c "create database tests;"
      - run:
          name: List Enabled Query Runners
          command: docker-compose run --rm redash manage ds list_types
      - run:
          name: Run Tests
          command: docker-compose run --name tests redash tests --junitxml=junit.xml --cov-report xml --cov=redash --cov-config .coveragerc tests/
      - run:
          name: Copy Test Results
          command: |
            mkdir -p /tmp/test-results/unit-tests
            docker cp tests:/app/coverage.xml ./coverage.xml
            docker cp tests:/app/junit.xml /tmp/test-results/unit-tests/results.xml
          when: always
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: coverage.xml
  frontend-lint:
    environment:
      CYPRESS_INSTALL_BINARY: 0
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 1
    docker:
      - image: circleci/node:14.17
    steps:
      - checkout
      - run: mkdir -p /tmp/test-results/eslint
      - run: sudo npm install --global --force yarn@1.22.10
      - run: yarn cache clean && yarn --frozen-lockfile --network-concurrency 1
      - run: yarn lint:ci
      - store_test_results:
          path: /tmp/test-results
  frontend-unit-tests:
    environment:
      CYPRESS_INSTALL_BINARY: 0
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 1
    docker:
      - image: circleci/node:14.17
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt install python3-pip
      - run: sudo npm install --global --force yarn@1.22.10
      - run: yarn cache clean && yarn --frozen-lockfile --network-concurrency 1
      - run:
          name: Run App Tests
          command: yarn test
      - run:
          name: Run Visualizations Tests
          command: (cd viz-lib && yarn test)
      - run: yarn lint
  frontend-e2e-tests:
    environment:
      COMPOSE_FILE: .circleci/docker-compose.cypress.yml
      COMPOSE_PROJECT_NAME: cypress
      PERCY_TOKEN_ENCODED: ZGRiY2ZmZDQ0OTdjMzM5ZWE0ZGQzNTZiOWNkMDRjOTk4Zjg0ZjMxMWRmMDZiM2RjOTYxNDZhOGExMjI4ZDE3MA==
      CYPRESS_PROJECT_ID_ENCODED: OTI0Y2th
      CYPRESS_RECORD_KEY_ENCODED: YzA1OTIxMTUtYTA1Yy00NzQ2LWEyMDMtZmZjMDgwZGI2ODgx
      CYPRESS_INSTALL_BINARY: 0
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 1
    docker:
      - image: circleci/node:14.17
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - checkout
      - run:
          name: Enable Code Coverage report for master branch
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              echo 'export CODE_COVERAGE=true' >> $BASH_ENV
              source $BASH_ENV
            fi
      - run: sudo npm install --global --force yarn@1.22.10
      - run:
          name: Install frontend dependencies
          command: yarn cache clean && yarn --frozen-lockfile --network-concurrency 1
      - run:
          name: Setup Redash server
          command: |
            yarn cypress build
            yarn cypress start -- --skip-db-seed
            docker-compose run cypress yarn cypress db-seed
      - run:
          name: Execute Cypress tests
          command: yarn cypress run-ci
      - run:
          name: "Failure: output container logs to console"
          command: |
            docker-compose logs
          when: on_fail
      - run:
          name: Copy Code Coverage results
          command: |
            docker cp cypress:/usr/src/app/coverage ./coverage || true
          when: always
      - store_artifacts:
          path: coverage
  build-docker-image: *build-docker-image-job
  build-preview-docker-image: *build-docker-image-job

  build_image:
    executor: google-sdk
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: auth
          command: |
            set -x
            touch $BASH_ENV
            source $BASH_ENV

            # CircleCIに対して割り当てられた認証情報でgclodコマンドを叩く
            echo ${CIRCLE_OIDC_TOKEN} > .cci.token

            export GCP_PROJECT_ID=cabakuru-analytics
            export GCP_PROJECT_NUMBER=791369243901

            export SERVICE_ACCOUNT_NAME=cci-oidc-${CIRCLE_PROJECT_REPONAME:-x}@${GCP_PROJECT_ID}.iam.gserviceaccount.com
            export WORKLOAD_IDENTITY_POOL_NAME=pool-cci
            export WORKLOAD_IDENTITY_POOL_PROVIDER=pool-provider-cci
            export GCP_WORKLOAD_IDENTITY_PROVIDER=projects/${GCP_PROJECT_NUMBER}/locations/global/workloadIdentityPools/${WORKLOAD_IDENTITY_POOL_NAME}/providers/${WORKLOAD_IDENTITY_POOL_PROVIDER}

            export GOOGLE_APPLICATION_CREDENTIALS=key.json
            gcloud iam workload-identity-pools create-cred-config \
              ${GCP_WORKLOAD_IDENTITY_PROVIDER} \
              --service-account=${SERVICE_ACCOUNT_NAME} \
              --output-file=${GOOGLE_APPLICATION_CREDENTIALS} \
              --credential-source-file=.cci.token \
              --credential-source-type=text

            echo Y | gcloud auth login --cred-file=${GOOGLE_APPLICATION_CREDENTIALS} --no-launch-browser
            gcloud config set project ${GCP_PROJECT_ID}
            gcloud auth configure-docker asia-northeast1-docker.pkg.dev
      - run:
          name: build
          command: |
            docker build -t redash/latest .
            docker tag redash/latest asia-northeast1-docker.pkg.dev/cabakuru-analytics/redash/redash:latest
            docker push asia-northeast1-docker.pkg.dev/cabakuru-analytics/redash/redash:latest

  deploy:
    executor: google-sdk
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: auth
          command: |
            set -x
            touch $BASH_ENV
            source $BASH_ENV

            # CircleCIに対して割り当てられた認証情報でgclodコマンドを叩く
            echo ${CIRCLE_OIDC_TOKEN} > .cci.token

            export GCP_PROJECT_ID=cabakuru-analytics
            export GCP_PROJECT_NUMBER=791369243901

            export SERVICE_ACCOUNT_NAME=cci-oidc-${CIRCLE_PROJECT_REPONAME:-x}@${GCP_PROJECT_ID}.iam.gserviceaccount.com
            export WORKLOAD_IDENTITY_POOL_NAME=pool-cci
            export WORKLOAD_IDENTITY_POOL_PROVIDER=pool-provider-cci
            export GCP_WORKLOAD_IDENTITY_PROVIDER=projects/${GCP_PROJECT_NUMBER}/locations/global/workloadIdentityPools/${WORKLOAD_IDENTITY_POOL_NAME}/providers/${WORKLOAD_IDENTITY_POOL_PROVIDER}

            export GOOGLE_APPLICATION_CREDENTIALS=key.json
            gcloud iam workload-identity-pools create-cred-config \
              ${GCP_WORKLOAD_IDENTITY_PROVIDER} \
              --service-account=${SERVICE_ACCOUNT_NAME} \
              --output-file=${GOOGLE_APPLICATION_CREDENTIALS} \
              --credential-source-file=.cci.token \
              --credential-source-type=text

            echo Y | gcloud auth login --cred-file=${GOOGLE_APPLICATION_CREDENTIALS} --no-launch-browser
            gcloud config set project ${GCP_PROJECT_ID}
            gcloud auth configure-docker asia-northeast1-docker.pkg.dev

            apt update && apt-get install -y jq
            ./deploy.sh

workflows:
  version: 2
  build:
    jobs:
      - backend-lint
      - backend-unit-tests:
          requires:
            - backend-lint
      - frontend-lint
      - frontend-unit-tests:
          requires:
            - backend-lint
            - frontend-lint
      - frontend-e2e-tests:
          requires:
            - frontend-lint
      - build-preview-docker-image:
          requires:
            - backend-unit-tests
            - frontend-unit-tests
            - frontend-e2e-tests
          filters:
            branches:
              only:
                - master
      - hold:
          type: approval
          requires:
            - backend-unit-tests
            - frontend-unit-tests
            - frontend-e2e-tests
          filters:
            branches:
              only:
                - /release\/.*/
      - build-docker-image:
          requires:
            - hold

  build_deploy:
    jobs:
      - deploy:
          context: global
          filters:
            branches:
              only:
                - kineca
